import type { Metadata } from 'next'
import Link from 'next/link'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
import moon from '../../public/Moon.svg'
import sun from '../../public/Sun.svg'
import Image from 'next/image'
import git from '../../assets/gitHub.svg'
import linkein from '../../assets/linkedIn.svg'
import inst from '../../assets//instagram.svg'

import { useAction } from '../../hooks/useAction'
import { useTypeSelector } from '../../hooks/useTypeSelector'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { theme, loading, error } = useTypeSelector((state) => state.theme)

  const { setTheme } = useAction()

  return (
    <>
      <nav className="navbar">
        <div className="container">
          <div className="navbar__row">
            <div className="navbar__logo">
              <Link href={'/'}>
                <strong>Frontend </strong>partfolio
              </Link>
            </div>
            <div
              onClick={() => {
                setTheme(!theme)
              }}
              className={`navbar__mode ${
                theme ? 'navbar__mode--ligh' : 'navbar__mode--dark'
              }`}
            >
              <Image src={sun} alt="" className="dark-mode" />
              <Image src={moon} alt="" className="light-mode" />
            </div>
            <div className="navbar__navigation">
              <Link href={'/'}>Projects</Link>
              <Link href={'/skills'}>Skills</Link>
              <Link href={'/contacts'}>Contacts</Link>
            </div>
          </div>
        </div>
      </nav>
      <div className={`content ${theme ? 'dark' : ''}`}>{children}</div>

      <footer>
        <div className="footer">
          <div className="footer__nav-link">
            <Link href={'https://github.com/leonVoyt'} target="_blank">
              <Image src={git} alt="" className="dark-mode" />
            </Link>
            <Link
              href={
                'https://www.linkedin.com/in/%D0%BB%D0%B5%D0%BE%D0%BD-%D0%B2%D0%BE%D0%B9%D1%82%D0%BA%D0%B5%D0%B2%D0%B8%D1%87%D1%83%D1%81-6b4627279/'
              }
              target="_blank"
            >
              <Image src={linkein} alt="" className="light-mode" />
            </Link>
            <Link
              href={'https://www.instagram.com/leo_vtkvchs/'}
              target="_blank"
            >
              <Image src={inst} alt="" className="light-mode" />
            </Link>
          </div>
          <p>All right`s reserved!</p>
        </div>
      </footer>
    </>
  )
}
