import type { Metadata } from 'next'
import Link from 'next/link'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
import moon from '../../public/Moon.svg'
import sun from '../../public/Sun.svg'

import Image from 'next/image'
import { useState } from 'react'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [check, setCheck] = useState(false)
  return (
    <>
      <nav className="navbar">
        <div className="container">
          <div className="navbar__row">
            <div className="navbar__logo">
              <Link href={'/'}>
                <strong>Frontend </strong>partfolio
              </Link>
            </div>
            <div
              onClick={() => {
                setCheck(!check)
                console.log(check)
              }}
              className={`navbar__mode ${check ? 'navbar__mode--ligh' : ''}`}
            >
              <Image src={sun} alt="" className="dark-mode" />
              <Image src={moon} alt="" className="light-mode" />
            </div>
            <div className="navbar__navigation">
              <Link href={'/projects'}>Projects</Link>
              <Link href={'/skills'}>Skills</Link>
              <Link href={'/contacts'}>Contacts</Link>
            </div>
          </div>
        </div>
      </nav>
      <div className="content">{children}</div>
    </>
  )
}
